### ISSUE TITLE
Choosing the Font

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#116]
**Suggestions:**

![fonts](https://user-images.githubusercontent.com/6609359/35261801-225a5334-0012-11e8-89cd-72a6045bd022.PNG)

@hetec what did you think?

**Comment by patrick-hebner** [comment]
![image](https://user-images.githubusercontent.com/6704069/35479792-06812db2-0400-11e8-9f04-d92b207f3387.png)

I also always like Robot but the Noto Sans looks also nice

**Comment by patrick-hebner** [comment]
What is your favorite?

**Comment by flashback2k14** [comment]
![bildschirmfoto 2018-01-28 um 11 55 20](https://user-images.githubusercontent.com/6609359/35481354-350b6220-0422-11e8-9e1e-1f6f7deab800.png)

this is Work Sans. It's a little thinner / sharper. This is my favorite.

**Comment by patrick-hebner** [comment]
Yes, looks also nice! We can start with this one and should make sure that we are able to simply change the font if needed.

**Comment by flashback2k14** [comment]
Okay. i will add the font into the wiki.
