### ISSUE TITLE
Choosing the Color Schema

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#117]
here is a nice website for [colors](http://khroma.co/).

You can import [my selected colors](https://drive.google.com/file/d/1e9LlHI7OphUOLDqnGTE-WOLEH-hWkz7Y/view?usp=sharing) here after you click the personalize button:
![bildschirmfoto 2018-01-28 um 12 00 40](https://user-images.githubusercontent.com/6609359/35481422-9124c316-0423-11e8-92e4-6793dcd8add8.png)

i really like dark themes and this looks nice:

![bildschirmfoto 2018-01-28 um 12 01 18](https://user-images.githubusercontent.com/6609359/35481437-f286f732-0423-11e8-8ac8-b62b5aea56a6.png)

or this

![bildschirmfoto 2018-01-28 um 12 01 07](https://user-images.githubusercontent.com/6609359/35481439-f50161d2-0423-11e8-93e3-5d49bd2066f7.png)

@hetec what did you think?

**Comment by patrick-hebner** [comment]
I also like dark themes but I don't think it's good choice for this kind of project. Because 'dark' in context of food mostly means that something is spoiled or stale. I would prefer green as primary color (we could also use some kind of mint green like yours) and different light grey colors (or white). I used this color pallet for my mock up
![colors](https://user-images.githubusercontent.com/6704069/35481845-49d25308-042c-11e8-8aac-c53dff5aa319.png)

**Comment by patrick-hebner** [comment]
I would also like to use a gradient out of the primary colors (like the last one)

**Comment by flashback2k14** [comment]
What did you think about this?

![bildschirmfoto 2018-01-28 um 15 30 15](https://user-images.githubusercontent.com/6609359/35483262-342b58ba-0440-11e8-9285-52e4cb708601.png)
[link](https://material.io/color/#!/?view.left=0&view.right=0&primary.color=69F0AE&secondary.color=607D8B&primary.text.color=37474F&secondary.text.color=FAFAFA)

maybe we could integrate a lite and a dark theme!?

**Comment by patrick-hebner** [comment]
Yes looks pretty nice. I think we can use this. In general I think we should keep all thinks like colors, fonts and so on in global sass variables so we can easily change them. This would also enable using a dark theme I think.

**Comment by flashback2k14** [comment]
Cool. :-) I have zero knowledge and experience about sass and working with it. 😎
