### ISSUE TITLE
ingredients or foods 

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#13]
This domain is not completely defined. There is still no consensus about the purpose of this component. Do we want a list of ingredients like in a fridge or just a collection of foods which can be used in the recipes (calculate calories ..., maybe crowd sourced)

**Comment by flashback2k14** [comment]
1. i think ingredients or fridge inventory items are only headlines and maybe show some different information of a food item!? **ToDo:** spec for food item!

2. crowd sourced is a very good idea. maybe we can grab some data from other providers like chefkoch, etc. to fill your initial database!?

**Comment by hetec** [comment]
Ok, so you would implement a collection of foods and provide different views of this foods?

**Comment by flashback2k14** [comment]
Yes, this was my intension. This reduce redundant items and the user doesn't need to create a tomato for the fridge and for the recipes for example.

**Comment by flashback2k14** [comment]
food item fields:
 - id: Number
 - name: String
 - amount: Number
 - unit: String
 - bestBefore: String
 - created: Number

@hetec what did you think? Need we more or other fields?

**Comment by hetec** [comment]
Looks ok. But I think we slowly need some kind of DB schema diagram or the like because I'm not sure if this item would also need a field for the user and recipe it belongs to?!

**Comment by flashback2k14** [comment]
Yea, you are right. I have created a DB Schema Diagram. [Link](https://drive.google.com/file/d/0B_-yrSSE644XX1cxT0hPR3BqUnc/view?usp=sharing)

What did you think @hetec?

![recipe](https://cloud.githubusercontent.com/assets/6609359/23313936/01376ac8-fac0-11e6-8f43-00c08bf94d28.png)

**Comment by flashback2k14** [comment]
@hetec short reminder :-)

**Comment by hetec** [comment]
Ok, this looks pretty good. Maybe some additions. We could add some columns to SocoboUserRecipeRelation:
isOwner: The owner with full access to all recipe features
isCollaborator: User who has read and write access
isReader: User with only read access
nothing means no access

**Comment by hetec** [comment]
Recipe:
isPublic Column: Everyone has read access to this recipe

**Comment by hetec** [comment]
I think FoodItem and IngredientItem are one and the same thing. There should just be a relationship table between the recipe and the foodItems which represents the ingredients

**Comment by hetec** [comment]
Do we also want a pool of public foodItems?

**Comment by hetec** [comment]
Do we want to add the diagramm to the wiki section?

**Comment by flashback2k14** [comment]
- Your additions sounds good. Could you add this into the diagram?
- yes, the fooditems should also be public and crowd sourced
- this is a good idea to put the diagram into the wiki

**Comment by hetec** [comment]
Yes I will do this this weekend

**Comment by hetec** [comment]
Fuck I had added my changes and they were not saved :( After that I noticed that the file is read only

**Comment by flashback2k14** [comment]
Sorry. I didn't know that.

**Comment by hetec** [comment]
No problem. I just think it is read only since there was stated last changed at ... (read only). Or do I need to save the file in draw io directly?

**Comment by flashback2k14** [comment]
I have no glue. I check it tomorrow. Maybe I missed some options.

**Comment by hetec** [comment]
ok

**Comment by flashback2k14** [comment]
Here is a new [Link](https://drive.google.com/file/d/0B_-yrSSE644XX1cxT0hPR3BqUnc/view?usp=sharing) with edit options @hetec .

**Comment by flashback2k14** [comment]
I think we should firstly extend / modify our database schema before we think about frontend stuff

ToDo:
- [ ] update database schema
- [ ] extend model classes
- [ ] create new model classes
- [ ] extend api and routes

@hetec

**Comment by hetec** [comment]
Ok, but I think we should limit the backend stuff we want to implement before starting with the frontend because the backend will always grow further.
And after implementing the extended schema and the related routes we should start all the frontend stuff associated with this.
And after reaching a stable state (frontend + backend) we should should start implementing features from as a whole, that meas we would always implement the frontend and backend of a feature before we start working on a new feature.

But at first I will update the diagramm

**Comment by hetec** [comment]
I have updated the schema diagram. Could you please verify the changes. Please excuse the formatting, but these db relationship lines are not very flexible.

**Comment by flashback2k14** [comment]
> Ok, but I think we should limit the backend stuff we want to implement before starting with the frontend because the backend will always grow further.
And after implementing the extended schema and the related routes we should start all the frontend stuff associated with this.
And after reaching a stable state (frontend + backend) we should should start implementing features from as a whole, that meas we would always implement the frontend and backend of a feature before we start working on a new feature.
But at first I will update the diagramm

i'm totally with you.

**Comment by flashback2k14** [comment]
> I have updated the schema diagram. Could you please verify the changes. Please excuse the formatting, but these db relationship lines are not very flexible.

I think its okay. the diagram look really messy. ;-) we should break it into smaller pieces? or maybe a better item order!? or we simply write the relations into plain text?
