### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#14]
Improve the error handling of the backend.

- uniform error object (already done)
- Provide ONLY clear error message to the client (no stacktrace)
- Log errors to a log file
- store error message in a central location like a messages file or object
- ...

**Comment by flashback2k14** [comment]
Maybe write errors to the Database instead of a log File. And create an API endpoint to get the errors!?

**Comment by hetec** [comment]
How would you handle db errors. Another point would be that you couldn't access your logs if the database is down.

**Comment by flashback2k14** [comment]
Okay. This was a Bad idea. :-)

**Comment by flashback2k14** [comment]
@hetec i have added same basic implementation. please check branch 14-Error-handling.
