### ISSUE TITLE
Shared folder for Models

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#16]
because we use TypeScript for frontend and backend.

-- SocoboPlusPlus
|-- client
|-- shared
|-- server

**Comment by hetec** [comment]
Thats a nice idea to reduce duplication! But I think this would couple the front end and the back end?! What would happen if the for instance the front end needs some slight changes of the model? These changes would also be introduced to the back end and if the back end cannot handle these changes we would also need to adapt the backend logic.

What do you think about this? I'm not sure whats the best tradeoff.

**Comment by flashback2k14** [comment]
Hmm, but the Models represents our Database schema and this should be the Same on both sides!?

**Comment by flashback2k14** [comment]
what do you think @lyio?
