### ISSUE TITLE
Add a new recipe

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#18]
- route for adding a new recipe
- create database service for recipes and implement the add function
- create db table

**Comment by flashback2k14** [comment]
i think we should first implement user login and registration!?

**Comment by hetec** [comment]
I think we can so this in parallel since user login should bei independent from the recipe service. Maybe a middleware which Hooksiel into the request chain before each recipe operation or so.

**Comment by flashback2k14** [comment]
Yes, you are right. But before I would complete the error handling.

**Comment by hetec** [comment]
Yes. You changes to the error  Handling look fine for me. I just have a question related to the spy. But im currently in the train anderen will ask you later via hangouts. If you are also happy with the state of the error handling you are encouraged to merge the PR 😉
