### ISSUE TITLE
Bug if you want to login with a username

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#33]
If several users were registered with email addresses like:

john@gmx.com,
john@gmail.com,
john@...

each of these accounts will get the username john. So if you now try to login as john an internal server error is thrown which tells you that multiple rows are not allowed. The query founds multiple rows because the username john exists 3 times in this case but should be unique.

"name": "QueryResultError",
      "stack": "QueryResultError: 2\n    at new QueryResultError (/Users/patrick/dev/socobo/SocoboPlusPlus/server/node_modules/pg-promise/lib/errors/queryResult.js:121:22)\n    at Query.<anonymous> (/Users/patrick/dev/socobo/SocoboPlusPlus/server/node_modules/pg-promise/lib/query.js:156:41)\n    at Query.handleReadyForQuery (/Users/patrick/dev/socobo/SocoboPlusPlus/server/node_modules/pg/lib/query.js:106:10)\n    at Connection.<anonymous> (/Users/patrick/dev/socobo/SocoboPlusPlus/server/node_modules/pg/lib/client.js:163:19)\n    at emitOne (events.js:101:20)\n    at Connection.emit (events.js:188:7)\n    at Socket.<anonymous> (/Users/patrick/dev/socobo/SocoboPlusPlus/server/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)",
      "message": "Multiple rows were not expected.",

**Comment by flashback2k14** [comment]
Hmm. Okay, than only register a new user is possible with E-Mail and provide an unique auto generated username like user123421. This username could be changed with the coming profile endpoint! What did you think @hetec?

**Comment by hetec** [comment]
I'm with you that we should enable the user to set the username in the user profile. Maybe we could initially set the user name also to the email address, so it would be unique and the user can change this to what ever he want in the profile later.

What

**Comment by flashback2k14** [comment]
Yes, thats even better, because we doesn't need extra logic to generate usernames.

**Comment by hetec** [comment]
I think we could also do this after merging #12

**Comment by flashback2k14** [comment]
Okay, but before merging #12 I would implement extend SocoboUser #28. Or should we merge #12 into master first?

**Comment by hetec** [comment]
You can do this first because I think #28 is very related to #12
