### ISSUE TITLE
improve JWT creation and validation

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#34]
- create JWT only with specific user fields
- create new middleware function inside AuthValidator called checkPayload() 
  - if the extracted user is a valid user 
  - if the user is allowed to access a specific endpoint, e.g. admin

**Comment by hetec** [comment]
Sounds good! What fields should go into the jwt? I saw that I had forgot to change the error in the auth validator. Maybe you could adapt this in the scope of this issue too.

**Comment by flashback2k14** [comment]
i would follow the [JWT claims](https://tools.ietf.org/html/rfc7519#section-4.1). 
```json 
{
  "iss": "socobo",
  "exp": "comes from the jwt module",
  "iat": "comes from the jwt module",
  "username": "user1234",
  "email": "mail@test.test",
  "admin": "true|false"
}
```

what did you think? is this enough? @hetec 

yes, i change the error object creation in this issue.

**Comment by hetec** [comment]
I think this is ok! I think we should add more public claims first if we need them.

**Comment by flashback2k14** [comment]
Yes, this is enough for this time.
