### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [socobo/SocoboPlusPlus#37]
Check out couple things:

* [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo)
* [schemats](https://github.com/sweetiq/schemats)

It might give you a better perspective at how to organize your database layer.

P.S. I'm the author of `pg-promise` :wink:

**Comment by flashback2k14** [comment]
Thanks for your hints @vitaly-t. 

@hetec we should definitely refactor our database layer by following the  [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo/tree/master/TypeScript) project. What do you think about?

**Comment by hetec** [comment]
I agree with that

**Comment by flashback2k14** [comment]
okay, i would say we start the refactoring process after merging all open branches into the master!?
1. merge Branch #28 into Branch #12 
2. merge Branch #12 into master. 
3. merge master into Branch #18 
4. merge Branch #18 into master

**Comment by hetec** [comment]
Ok
