### ISSUE TITLE
add typescript linting

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#38]
- [tslint Rules](https://palantir.github.io/tslint/rules/)
- [default Rules](https://github.com/palantir/tslint/tree/master/src/configs)

**Comment by flashback2k14** [comment]
short reminder for myself:

<details>
  <summary>stashed changes</summary>
  stash@{0}: WIP on 12-user-management: 4779415 Merge pull request #32 from socobo/27- improve-error-handling
</details>

**Comment by hetec** [comment]
I really agree with this issue. So i hopefully don't forget so many semicolons ;)

**Comment by flashback2k14** [comment]
Hehe. Yes, linting is really helpful. :-)
