### ISSUE TITLE
DB layer refactoring

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#39]
See also #37

**Comment by flashback2k14** [comment]
I think we should start the implementation after the issues #33, #34, #37 and #42.

**Comment by flashback2k14** [comment]
- [ ] #33 
- [ ] #34 
- [ ] #38
- [ ] #42

**Comment by flashback2k14** [comment]
@hetec After closing all referenced issues we can start the refactoring.

**Comment by hetec** [comment]
Yes I also think that we're ready now. Do you want to do this or should I do it?

**Comment by flashback2k14** [comment]
You can start the refactoring and I look into your commits and tell you what I like or dislike. ;-)

**Comment by hetec** [comment]
Sound good!
