### ISSUE TITLE
Remove user from the request body

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#42]
We have a problem with the auth validator. The user is directly appended to the req.body. But if we want to add resources like recipes or other item the user is mixed into these object and we get something like this:

{
  "title": "test",
  "userId": 1,
  "description": "Test Desc",
  "imageUrl": "http://someimage.jpg",
  "decoded": {
    "id": 3,
    "username": "pat",
    "email": "pat@test.com",
    "password": "$2a$10$N7vJc1VUgbrq7nEgmCMPXugRg.YC6RviQ6ZWQETZW2F1edGnWPkmu",
    "image": "http://placehold.it/350x150",
    "hastermsaccepted": true,
    "isadmin": true,
    "provider": "email",
    "created": "1484548879642",
    "lastmodified": "1484548879642",
    "iat": 1484599012,
    "exp": 1484685412
  },
  "created": "2017-01-17T20:11:06.841Z",
  "id": 24
}

Decoded should not be part of the recipe! I think we should add the user to the req object itself rather than to the body object?!

**Comment by flashback2k14** [comment]
Yes, this is not good. I have added this to the body for type compatibility. If we add decoded to req, than we must use req: any instead of req: Request as function parameter. But this should be fixed if issue #34 is implemented. I have planned to remove the decoded object after the user check.

**Comment by hetec** [comment]
Ok if #34 will fix this everything is fine

**Comment by hetec** [comment]
I will close this issue since this was fixed in #34
