### ISSUE TITLE
user profile

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#43]
functions:
- [ ] change username
- [ ] change email
- [ ] change profile image
- [ ] change password
- [ ] change aboutMe --> ToDo: Extend SocoboUser
- [ ] reset password
- [ ] delete account

**Comment by flashback2k14** [comment]
@hetec  what did you think?

**Comment by hetec** [comment]
Why a biography?

**Comment by flashback2k14** [comment]
because every social portal has a field for personal information. :-) have you a better name?

**Comment by hetec** [comment]
Maybe just a simple 'about me' section?

**Comment by flashback2k14** [comment]
Okay.
