### ISSUE TITLE
refactoring user registration

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#44]
- [x]  use ExtractRequestBodyResult for authService.register and authService.login function parameter
- [x] only allow registration with email
- [x] register new user inside promise.then() not promise.catch() --> this could maybe fixed with issue #39

**Comment by hetec** [comment]
How do you get this error? If I try to register twice with the same email I got the error AUTH_USED_PASSWORD_EMAIL

**Comment by flashback2k14** [comment]
yes, you are right. the error come from the username. i have tested with a wrong email.

```json
{
    "name": "error",
    "source": "UserService",
    "sourceMethod": "save(..)",
    "error": {
      "name": "error",
      "length": 219,
      "severity": "ERROR",
      "code": "23505",
      "detail": "Key (username)=(JohnDoe) already exists.",
      "schema": "public",
      "table": "socobo_user",
      "constraint": "socobo_user_username_key",
      "file": "nbtinsert.c",
      "line": "424",
      "routine": "_bt_check_unique"
    },
    "message": "Internal server error",
    "statusCode": 500,
    "code": "00001",
    "timestamp": 1484776451495
  }
```

**Comment by flashback2k14** [comment]
but i think the registration inside the catch is not so nice!?
