### ISSUE TITLE
extend database functionality

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#75]
this is the main issue for following tasks:
- [x] update database schema (simplify or restructure)  [Link](https://drive.google.com/file/d/0B_-yrSSE644XX1cxT0hPR3BqUnc/view?usp=sharing) [Diagram](https://www.draw.io/?state=%7B%22ids%22:%5B%220B_-yrSSE644XX1cxT0hPR3BqUnc%22%5D,%22action%22:%22open%22,%22userId%22:%22103183073414466549375%22%7D#G0B_-yrSSE644XX1cxT0hPR3BqUnc  )
- [x] extend model classes
- [x] create new model classes
- [x] extend api 
- [x] extend routes

Related Issues:

- [x] #76 Recipe Steps 
- [x] #77 SocoboUser New DB schema

branch __75-extend-database-functionality__ is the base branch for the sub tasks.

**Comment by hetec** [comment]
How do you want to simplify the database model? Do you want to remove some functions like sharing data?
The more I look at this database model, the more I get the feeling that the nosql database model of the first Socobo Project was somehow simpler.

**Comment by hetec** [comment]
I think we should organize the subtasks around parts of the database model like ingredients, units or the steps for the recipes, so that we get a structure like this:
ingredients:
- endpoints
- database service
- model classes
- routes

unit
- endpoints
- model classes
- database service
- routes

....

**Comment by flashback2k14** [comment]
Not the model is the problem. More the diagram. Maybe we should write down the relations like I have started!? Yes, maybe GraphQL is a better solution, but so much time spending to deal with postgres.

**Comment by flashback2k14** [comment]
The new project structure sounds good. All on one place. +1

**Comment by hetec** [comment]
No idea how GraphQL works, is it a full replacement of postgres? Ist it a database or just a query language?
Yes u are right, we have already invested  a lot in all this postgres stuff, and we would need to reimplement the existing db layer if we switch to another solution.

**Comment by hetec** [comment]
Maybe we should create two diagrams. One which only contains the entities with their fields and no relations. And one which contains only relations and entity names (and if needed a textual description)

**Comment by flashback2k14** [comment]
Hmm. If I read it right than is it only a query language. We should definitly stay with our solution. 

Yes, that sounds great. we should do this. :-)

**Comment by flashback2k14** [comment]
@hetec could you please verify, modify or extend my newly created database diagram (link above)!?

**Comment by hetec** [comment]
@flashback2k14 I added my ideas and thoughts to the diagram (see coloured areas). Thanks for the new diagram! This one looks much better!

**Comment by flashback2k14** [comment]
@hetec thanks for your additions. I would keep the created and modified date fields. maybe we need it later. I'm not really sure if i get it right with the foodItemTemplate. I have added some questions!

**Comment by hetec** [comment]
@flashback2k14 I have answered your question and I hope it makes it a bit clearer. Maybe there is a better solution?
It's OK if you want to keep the 'created' fields. I just had no idea for any usage of these.

**Comment by flashback2k14** [comment]
@hetec i have finished the db schema. I think we are done and can start with the implementation!?
