### ISSUE TITLE
Need Help with typegoose

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#88]
If use recipe as the Model Class (with typegoose decorators) I always get the error:

TypeError: Cannot assign to read only property 'title' of object '#<Recipe>'

if I try to set a value of the recipe Object. Like in the clone method. Do you have any idea what's the problem here? Does typegoose makes all fields readonly?

**Comment by flashback2k14** [comment]
Yes, that's the problem why our validation is not working or our set methods. I think we should not use typegoose here is a good example without typegoose [link](https://gist.github.com/brennanMKE/ee8ea002d305d4539ef6)

**Comment by flashback2k14** [comment]
@hetec please take a look into my new commit. I have removed Typegoose and this fixed the problem.

**Comment by hetec** [comment]
@flashback2k14 I will do this, thank you! I think removing typegoose is really the simplest solution in this case.
