### ISSUE TITLE
Do we want to maintain the tests

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#92]
Do we really want to maintain the tests further? I think we don't really use them and extend them, but we alway have to adapt them. That's annoying.

**Comment by flashback2k14** [comment]
After I have started to test my routes. I have found bugs and could fix it. I think we should test the routes. It should cover all interesting parts and points to bugs.

**Comment by hetec** [comment]
Ok, with focus on routes testing

**Comment by hetec** [comment]
I will reimplement my recipe route tests later in the same way you did with the auth routes for instance. Mocking each req and res object was a pain. I don't want to keep doing this. I think using a real request here would be much better.

**Comment by flashback2k14** [comment]
Yeah. This was much simpler than mocking the stuff and you test with real data.
